main:
  - name: Over mij
    url: /over-mij
    weight: 20
  - name: Expertise
    url: /expertise
    weight: 30
  - name: F.A.Q.
    url: /faq
    weight: 40
  - name: Contact
    url: /contact
    weight: 50
