# -- Site specifieke params
author: "QenA Verzuimadvies"
description: "Persoonlijke verzuimbegeleiding en re-integratieadvies voor MKB-bedrijven. QenA Verzuimadvies biedt deskundige ondersteuning bij verzuim, re-integratie en conflictbemiddeling"
keywords:
  - verzuimbegeleiding
  - re-integratieadvies
  - verzuimadvies
  - verzuimbegeleiding MKB
  - re-integratie MKB
favicon: "/images/favicon.ico"
logo: "/uploads/logo.webp"


# -- SEO params --
seo:
  enable: true
  twitter_card: "summary_large_image"
  og_image: "/uploads/og-logo.jpg"

# -- Schema --
schema:
  type: "Organization"
  name: "QenA Verzuimadvies"
  url: "https://qenaverzuimadvies.nl"
  logo: "/uploads/og-logo.jpg"
  sameAs:
    - "https://www.linkedin.com/in/annemiek-ooms-7a58081a/"

# -- Socials --
socials:
  - title: "linkedin"
    link: "https://www.linkedin.com/in/annemiek-ooms-7a58081a/"
    logo_image: /img/linkedin.svg
  - title: "whatsapp"
    link: "https://wa.me/+31620670466"
    logo_image: /img/whatsapp.svg