backend:
  name: git-gateway
  repo: GorillaMade/qenaverzuimadvies
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/d8762ed9-095d-4751-92ed-2782d2bb19a5/pkce
  auth_token_endpoint: /sites/d8762ed9-095d-4751-92ed-2782d2bb19a5/token
  gateway_url: https://gateway.decapbridge.com

# See who did what (optional)
commit_messages:
  create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
  update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
  delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
  uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
  deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
  openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://qenaverzuimadvies.nl

# Media folder
media_folder: "static/uploads"
public_folder: "/uploads"

#Collections
collections:
  - name: "site_config"
    label: "Site instellingen"
    files:
      - name: "config"
        label: "Algemene Hugo config"
        file: "config/_default/config.yml"
        format: "yaml"
        editor:
          preview: false
        fields:
          - label: "Base URL"
            name: "baseURL"
            widget: "string"
          - label: "Website titel"
            name: "title"
            widget: "string"
          - label: "Thema"
            name: "theme"
            widget: "string"
          - label: "Robots.txt inschakelen"
            name: "enableRobotTXT"
            widget: "boolean"
          - label: "Taalcode"
            name: "languageCode"
            widget: "string"
          - label: "Standaard inhoudstaal"
            name: "defaultContentLanguage"
            widget: "string"

      - name: "languages"
        label: "Talen instellingen"
        file: "config/_default/languages.yml"
        format: "yaml"
        editor:
          preview: false
        fields:
          - label: "Nederlands"
            name: "nl"
            widget: "object"
            fields:
              - label: "Taal naam"
                name: "languageName"
                widget: "string"
              - label: "Content map"
                name: "contentDir"
                widget: "string"
              - label: "Volgorde"
                name: "weight"
                widget: "number"
              - label: "Uitgeschakeld"
                name: "disabled"
                widget: "boolean"
              - label: "Params"
                name: "params"
                widget: "object"
                fields:
                  - label: "Vlag"
                    name: "flag"
                    widget: "string"
              - label: "Permalinks"
                name: "permAlinks"
                widget: "object"
                fields:
                  - label: "Pagina"
                    name: "page"
                    widget: "object"
                    fields:
                      # - label: "Posts"
                      #   name: "posts"
                      #   widget: "string"
                      #   default: "/blog/:slug"
                      - label: "Services"
                        name: "services"
                        widget: "string"
                        default: "/expertise/:slug"
                  - label: "Sectie"
                    name: "section"
                    widget: "object"
                    fields:
                      # - label: "Posts"
                      #   name: "posts"
                      #   widget: "string"
                      #   default: "/blog/"
                      - label: "Services"
                        name: "services"
                        widget: "string"
                        default: "/expertise/"

      - name: "menu"
        label: "Menu instellingen"
        file: "config/_default/menus.yml"
        format: "yaml"
        editor:
          preview: false
        fields:
          - label: "Menu items"
            name: "main"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - label: "Naam"
                name: "name"
                widget: "string"
              - label: "Pagina referentie"
                name: "url"
                widget: "string"
              - label: "Volgorde"
                name: "weight"
                widget: "number"

      - name: "params"
        label: "Algemene parameters"
        file: "config/_default/params.yml"
        format: "yaml"
        editor:
          preview: false
        fields:
          - label: "Auteur"
            name: "author"
            widget: "string"
          - label: "Beschrijving"
            name: "description"
            widget: "text"
          - label: "Keywords"
            name: "keywords"
            widget: "list"
            field:
              label: "Keyword"
              name: "keyword"
              widget: "string"
          - label: "Favicon"
            name: "favicon"
            widget: "image"
          - label: "Logo"
            name: "logo"
            widget: "image"
          - label: "SEO instellingen"
            name: "seo"
            widget: "object"
            fields:
              - label: "Ingeschakeld"
                name: "enable"
                widget: "boolean"
              - label: "Twitter kaart"
                name: "twitter_card"
                widget: "string"
              - label: "OG image"
                name: "og_image"
                widget: "image"
          - label: "Schema"
            name: "schema"
            widget: "object"
            fields:
              - label: "Type"
                name: "type"
                widget: "string"
              - label: "Naam"
                name: "name"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Logo"
                name: "logo"
                widget: "image"
              - label: "Sociale links"
                name: "sameAs"
                widget: "list"
                field:
                  label: "URL"
                  name: "url"
                  widget: "string"
          - label: "Socials"
            name: "socials"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"
              - label: "URL"
                name: "link"
                widget: "string"
              - label: "Logo"
                name: "logo_image"
                widget: "image"

  - name: "home"
    label: "Home pagina"
    files:
      - name: "home"
        label: "Homepagina content"
        file: "content/nl/_index.md"
        format: "frontmatter"
        fields:
          - label: "Pagina titel"
            name: "title"
            widget: "string"
          - label: "Pagina beschrijving"
            name: "description"
            widget: "text"
          - label: "Meta informatie"
            name: "meta"
            widget: "object"
            fields:
              - label: "Meta titel"
                name: "title"
                widget: "string"
              - label: "Meta beschrijving"
                name: "description"
                widget: "text"
          - label: "Pagina inhoud"
            name: "body"
            widget: "markdown"

  - name: "about"
    label: "Over mij pagina"
    files:
      - name: "about"
        label: "Over mij content"
        file: "content/nl/over-mij.md"
        format: "frontmatter"
        fields:
          - label: "Pagina titel"
            name: "title"
            widget: "string"
          - label: "Pagina beschrijving"
            name: "description"
            widget: "text"
          - label: "Meta informatie"
            name: "meta"
            widget: "object"
            fields:
              - label: "Meta titel"
                name: "title"
                widget: "string"
              - label: "Meta beschrijving"
                name: "description"
                widget: "text"
          - label: "Pagina inhoud"
            name: "body"
            widget: "markdown"

  - name: "expertise"
    label: "Expertise pagina"
    files:
      - name: "expertise"
        label: "Expertise content"
        file: "content/nl/expertise.md"
        format: "frontmatter"
        fields:
          - label: "Pagina titel"
            name: "title"
            widget: "string"
          - label: "Pagina beschrijving"
            name: "description"
            widget: "text"
          - label: "Meta informatie"
            name: "meta"
            widget: "object"
            fields:
              - label: "Meta titel"
                name: "title"
                widget: "string"
              - label: "Meta beschrijving"
                name: "description"
                widget: "text"
          - label: "Pagina inhoud"
            name: "body"
            widget: "markdown"

  - name: "faq"
    label: "FAQ pagina"
    files:
      - name: "faq"
        label: "FAQ content"
        file: "content/nl/faq.md"
        format: "frontmatter"
        fields:
          - label: "Pagina titel"
            name: "title"
            widget: "string"
          - label: "Pagina beschrijving"
            name: "description"
            widget: "text"
          - label: "Meta informatie"
            name: "meta"
            widget: "object"
            fields:
              - label: "Meta titel"
                name: "title"
                widget: "string"
              - label: "Meta beschrijving"
                name: "description"
                widget: "text"
          - label: "Pagina inhoud"
            name: "body"
            widget: "markdown"

  - name: "contact"
    label: "Contact pagina"
    files:
      - name: "contact"
        label: "Contact content"
        file: "content/nl/contact.md"
        format: "frontmatter"
        fields:
          - label: "Pagina titel"
            name: "title"
            widget: "string"
          - label: "Pagina beschrijving"
            name: "description"
            widget: "text"
          - label: "Meta informatie"
            name: "meta"
            widget: "object"
            fields:
              - label: "Meta titel"
                name: "title"
                widget: "string"
              - label: "Meta beschrijving"
                name: "description"
                widget: "text"
          - label: "Pagina inhoud"
            name: "body"
            widget: "markdown"

  - name: "services"
    label: "Expertise"
    folder: "content/nl/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "reviews"
    label: "Reviews"
    files:
      - name: "reviews"
        label: "Reviews (NL)"
        file: "data/nl/reviews.yaml"
        format: "yaml"
        editor:
          preview: false
        fields:
          - label: "Reviews"
            name: "reviews"
            widget: "list"
            summary: "{{fields.name}} – {{fields.stars}}★"
            fields:
              - label: "Naam"
                name: "name"
                widget: "string"

              - label: "Functie"
                name: "function"
                widget: "string"

              - label: "Afbeelding"
                name: "image"
                widget: "image"
                required: false

              - label: "Review tekst"
                name: "description"
                widget: "text"

              - label: "Sterren"
                name: "stars"
                widget: "number"
                value_type: "int"
                min: 1
                max: 5

  - name: "faqs"
    label: "FAQs"
    files:
      - name: "faqs"
        label: "FAQ pagina"
        file: "data/nl/faqs.yaml"
        format: "yaml"
        editor:
          preview: false
        fields:
          - label: "FAQ categorieën"
            name: "faqs"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"

              - label: "Vragen"
                name: "faqs"
                widget: "list"
                summary: "{{fields.question}}"
                fields:
                  - label: "Vraag"
                    name: "question"
                    widget: "string"

                  - label: "Antwoord"
                    name: "answer"
                    widget: "text"